### ISSUE TITLE
Pass in API key via header instead of URL param

### ISSUE THREAD

**Issue by arkon** [cobalt-uoft/cobalt#39]
Presently, API keys are passed in via the URL, like so:

```
https://cobalt.qas.im/api/1.0/buildings/080?key=API_KEY
```

It's better to pass it in as the `Authorization` header of the HTTP request, so it isn't as easily exposed.

**Comment by qasim** [comment]
As to prevent breaking the current API, we'd still have to keep the key parameter as an option, do you think something like this would be good?

``` js
let key = req.get('authorization') || req.query.key || false
if (!key) {
  let err = new Error('A valid API key must be provided.')
  err.status = 400
  return next(err)
}
```

We still aren't really keeping the API key secure since its stored in that authorization header as plain text, but it won't be exposed as easily when sharing URLs etc.

Then we would subsequently update the documentation to advertise the recommended authorization method.

**Comment by arkon** [comment]
Yup, that makes sense to me.

**Comment by qasim** [comment]
✅
