### ISSUE TITLE
GET courses doesn't return any locations.

### ISSUE THREAD

**Issue by jonnyli1125** [cobalt-uoft/cobalt#84]
for the location field, empty string is returned always, rather than the expected building code.

**Comment by kashav** [comment]
Just to clarify the issue – `/api/1.0/courses/filter?q=location:!""` is returning `[]`.

Not entirely sure why this is happening, @qasim should be able to inspect the db/logs and determine the exact reason when he gets the chance.

The most recent courses [dataset](https://raw.githubusercontent.com/cobalt-uoft/datasets/master/courses.json) includes the actual locations though, so it seems like the live API is using an outdated dataset (possibly a sync issue).

**Comment by qasim** [comment]
This seems to be fixed.

@kshvmdn As for [/api/1.0/courses/filter?q=location:!""](https://cobalt.qas.im/api/1.0/courses/filter?q=location:!""&key=), at first the syntax is a bit misleading. It could be interpreted as `not empty`, but what it means is `does not contain the empty string`. Since all location fields contain the empty string (vacuously), then no course is returned.
